### ISSUE TITLE
JSON post data

### ISSUE THREAD

**Issue by iceydee** [matt-42/silicon#27] opened 2016-04-07 13:23 UTC
I'd like to accept JSON post data instead of form-data. ie.

```
{"email":"my_email@email.com","password":"1234567"}
```

Instead of:
```
email=my_email@email.com&password=1234567
```

**Comment by tex** [comment] 2016-04-07 13:29
duplicate of #24 ?

**Comment by matt-42** [comment] 2016-04-07 13:46
Update to the last version of master, this has been implemented in the last commit:
https://github.com/matt-42/silicon/commit/e02c1ee222bac41ab8a4d58c5f713b30d2ec7e24#diff-ca334d1611153b304440f66073607b47R221

**Closed by matt-42** 2016-04-07 13:46 UTC
